apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-sa   # Identity used by my application
  namespace: default
  labels:
    app: nginx-deploy

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-role
  namespace: default

rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]     # Can only view pods but cannot create or delete pods

---
# Bind the role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-binding
  namespace: default

subjects:
- kind: ServiceAccount
  name: nginx-sa
  namespace: default

roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io

# Principle of Least Privilege:
# nginx-sa receives only the permissions required by the workload.
# If the workload is compromised, the attacker's Kubernetes permissions
# are limited to getting and listing pods in this namespace.