apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
type: Opaque          #Generic Secret 
data:
  message: SGVsbG8=    #Base64 Encoded and it Decode means : Hello.  
                       #IT means “Store ‘Hello’ securely as a secret”