name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write      #Giving Github permission to use OIDC token to push to azure

env:
  IMAGE_NAME: secure-nginx
  IMAGE_TAG: ${{ github.sha }}
  REGISTRY : securek8sacr01.azurecr.io   #To push to Azure Acr

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}      #Added Azure to Github login using OIDS

          # Adding Tags to the push image as it logins and push to Azure Acr
      - name:    Login to Azure container Registry
        run : |
            az acr login --name securek8sacr01
        
      - name:   Tag Docker Image For ACR 
        run: |
          docker tag \
            ${{ env.IMAGE_NAME}}:${{ env.IMAGE_NAME}} \
            ${{ env.REGISTRY}}/${{ env.IMAGE_NAME}}:${{ env.IMAGE_TAG}}

      - name:   PUSH Docker Image to ACR 
        run: |
          docker push \
            ${{ env.REGISTRY}}/${{ env.IMAGE_NAME}}:${{ env.IMAGE_TAG}}

      - name: Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Trivy container image scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          severity: HIGH,CRITICAL
          ignore-unfixed: true